---
# tasks file for overriding systemd upgrade timer

- name: Verify calendar variable
  ansible.builtin.command:
    cmd: systemd-analyze calendar {{ unattended_upgrades_upgrade_timer_oncalendar }}
  register: 'systemd_analyze_calendar'
  failed_when: systemd_analyze_calendar.rc > 0
  changed_when: false

- name: Create systemd directory
  ansible.builtin.file:
    path: '/etc/systemd/system/apt-daily-upgrade.timer.d'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Override systemd upgrade timer
  ansible.builtin.template:
    src: apt-daily-upgrade.timer.override.j2
    dest: '/etc/systemd/system/apt-daily-upgrade.timer.d/override.conf'
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
